### ISSUE TITLE
Warning: Call-time pass-by-reference has been deprecated

### ISSUE THREAD

**Issue by Tuckie** [unclecheese/KickAssets#1]
My install doesn't seem too happy with `$file->updateCMSFields(&$fields);`

```
Warning: Call-time pass-by-reference has been deprecated in /srv/www/htdocs/intranet/kickassets/code/KickAssetAdmin.php on line 567
```

Seems to popup everywhere

**Comment by unclecheese** [comment]
What version of PHP? That ampersand shouldn't be there. There's no need to pass by reference in PHP5 if the variable is an object.

---

SilverStripe tips, tutorials, screencasts and more: http://www.leftandmain.com

**Comment by Tuckie** [comment]
Its php 5.2.14, and your ampersand: https://github.com/unclecheese/KickAssets/blob/master/code/KickAssetAdmin.php#L567

**Comment by unclecheese** [comment]
Fixed!

**Comment by Tuckie** [comment]
(Not a hard bug to fix, but...) Much thanks!

**Comment by MarcusDalgren** [comment]
Umm I just downloaded the latest version and there's still an ampersand in there. The code looks like this:
            if(version_compare(PHP_VERSION, '5.3')) {
                $file->updateCMSFields(&$fields);  
            }
            else {
                $file->updateCMSFields($fields);  
            }
I'm running version 5.2.11 but I'm still getting an error related to this. It's on line 600 in KickAssetAdmin.php. 
Maybe it wasn't merged in yet?

**Comment by unclecheese** [comment]
5.3 wants it, 5.2 doesn't. That version compare should say >= 0.

**Comment by timsnadden** [comment]
This causes a fatal error for me in php 5.4.

Fatal error: Call-time pass-by-reference has been removed in /path/to/kickassets/code/KickAssetAdmin.php on line 684
